Needed to avoid this additional error when log tests fail:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
    File "C:\Program Files\Python39\lib\logging\__init__.py", line 2129, in shutdown
    h.flush()
    File "C:\...\.tox\opentelemetry-sdk\lib\site-packages\opentelemetry\sdk\_logs\__init__.py", line 373, in flush
    self._log_emitter_provider.force_flush()
AttributeError: 'DummyLogEmitterProvider' object has no attribute 'force_flush'