Fix example tests on Win32.
They were previously failing with

    OSError: [WinError 193] %1 is not a valid Win32 application

Since subprocess.Popen directly calls CreateProcess and the Windows
kernel doesn't support shebangs (even if it did, /usr/bin/env is not a
path that leads to a valid executable usually), we need to manually
specify sys.executable ('python' would not work since it would leave the
virtualenv).