docs: using correct python specifier for docs action (#1293)
There is a build error with the docs Github action currently,
that is due to incorrect Python specifier syntax.

	Run actions/setup-python@v2
	Version py38 was not found in the local cache
	Error: Version py38 with arch x64 not found
	The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json